/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ygapp_2013_JniDemo */

#ifndef _Included_com_example_ygapp_2013_JniDemo
#define _Included_com_example_ygapp_2013_JniDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ygapp_2013_JniDemo
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ygapp_12013_JniDemo_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ygapp_2013_JniDemo
 * Method:    stringFromJNI_2
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ygapp_12013_JniDemo_stringFromJNI_12
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ygapp_2013_JniDemo
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_ygapp_12013_JniDemo_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
